import type { Metadata } from "next";

// import { Open_Sans } from "next/font/google";

import "./globals.scss";

import { Header } from "../components/Header/index";
import { Footer } from "../components/Footer/index";

// const OpenSans = Open_Sans({ weight: ["400", "700", "800"] });

export const metadata: Metadata = {
  title: "Hungry",
  description: "Generated by create Shm",
  icons: {
    icon: ["/logo/favicon.ico?v=4"],
    apple: ["/logo/apple-touch-icon.png?v=4"],
    shortcut: ["/logo/apple-touch-icon.png"],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* className={OpenSans.className} */}
      <body>
        <div className="container">
          <Header />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
