import type { Metadata } from "next";

import "./globals.scss";
import "../scss/style.scss";

import { Header } from "../components/Header/index";
import { Footer } from "../components/Footer/index";

export const metadata: Metadata = {
  title: "Humgry",
  description: "Generated by create Shm",
  icons: {
    icon: ["/logo/favicon.ico?v=4"],
    apple: ["/logo/apple-touch-icon.png?v=4"],
    shortcut: ["/logo/apple-touch-icon.png"],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="container">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
