import type { Metadata } from "next";

import { Roboto } from "next/font/google";

import "../globals.scss";

import { Header } from "../../components/Header/index";
import { Footer } from "../../components/Footer/index";
import { Providers } from "../../components/Providers";
import { ReactNode } from "react";
import { unstable_setRequestLocale } from "next-intl/server";

type Props = {
  children: ReactNode;
  params: { locale: string };
};

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Hungry",
  description: "Generated by create Shm",
  icons: {
    icon: ["/logo/favicon.ico?v=4"],
    apple: ["/logo/apple-touch-icon.png?v=4"],
    shortcut: ["/logo/apple-touch-icon.png"],
  },
};

export default function LocaleLayout({ children, params: { locale } }: Props) {
  // Enable static rendering
  unstable_setRequestLocale(locale);
  return (
    <html lang={locale} className={roboto.className}>
      <body>
        <Providers>
          <Header />
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
